pr: none
trigger:
- master

pool:
  vmImage: Ubuntu-16.04

steps:

- script: |
    git submodule update --init
  displayName: 'Fetch submodules'

- script: |
    sudo chown -R $USER $CONDA
    . $CONDA/etc/profile.d/conda.sh
    conda env update --prefix ./env -f exoplanet/environment.yml --prune
    conda activate ./env
    python -m pip install -U -r requirements-notebooks.txt
    python -m pip install -e ./exoplanet
    CACHEDIR=`pwd`/theano_cache
    export THEANO_FLAGS=base_compiledir=$CACHEDIR
  displayName: 'Setup conda'

- script: |
    echo $THEANO_FLAGS
    which python
