pr: none
trigger:
- master

pool:
  vmImage: Ubuntu-16.04

variables:
  conda_path: $(Pipeline.Workspace)/conda
  output_path: $(Build.ArtifactStagingDirectory)

steps:

- script: |
    git submodule update --init
    sudo chown -R $USER $CONDA
  displayName: 'Setup'

- task: Cache@2
  inputs:
    key: conda | $(Agent.OS) | exoplanet/environment.yml | requirements-notebooks.txt
    path: $(conda_path)
    cacheHitVar: CACHE_RESTORED

- script: .ci/azure/install_deps.sh
  displayName: 'Install dependencies'
  condition: ne(variables.CACHE_RESTORED, 'true')

- script: .ci/azure/run_notebooks.sh
  displayName: 'Run notebooks'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(output_path)
    artifactName: Notebooks
