pr: none
trigger:
- master

pool:
  vmImage: Ubuntu-16.04

steps:

- script: |
    git submodule update --init
  displayName: 'Fetch submodules'

- script: |
    sudo chown -R $USER $CONDA
    . $CONDA/etc/profile.d/conda.sh
    conda env update --prefix ./env -f exoplanet/environment.yml -q --prune
    conda activate ./env
    python -m pip install -U -r requirements-notebooks.txt
    python -m pip install -e ./exoplanet
    conda env export > $(Build.ArtifactStagingDirectory)/environment.yml
  displayName: 'Setup conda'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate ./env
    export THEANO_FLAGS=base_compiledir=`pwd`/theano_cache
    cd docs
    python run_notebooks.py notebooks/rv.ipynb
  displayName: 'Run notebooks'

- script: |
    cp docs/_static/notebooks/*.ipynb $(Build.ArtifactStagingDirectory)
    cp docs/notebooks/notebook_setup.py $(Build.ArtifactStagingDirectory)
    cp docs/notebook_errors.log $(Build.ArtifactStagingDirectory)
  displayName: 'Save generated notebooks'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Notebooks
