name: Tutorials
on:
  push:
    branches:
      - main
  pull_request:
    branches:
  release:
    types:
      - published

jobs:
  notebooks:
    name: ${{ matrix.notebook-name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook-name:
          - docs/tutorials/tess.py
          - docs/tutorials/together.py
          - docs/tutorials/eb.py
          - docs/tutorials/quick-tess.py
          - docs/tutorials/lc-multi.py
          - docs/tutorials/stellar-variability.py
          - docs/tutorials/ttv.py
          - docs/tutorials/rv-multi.py
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Execute the notebooks
        run: |
          jupytext --to ipynb --execute $NOTEBOOK_NAME
        env:
          NOTEBOOK_NAME: ${{ matrix.notebook-name }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ hashFiles('docs/tutorials/*.ipynb') }}
          path: docs/tutorials/*.ipynb

  combine:
    name: Combine results
    needs: notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Move the files
        run: |
          mkdir -p docs/tutorials
          find . -name \*.ipynb -exec cp {} docs/tutorials \;
          ls .
          ls docs/tutorials
      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/tutorials
      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
